# Site settings
title: "Kasey McFadden"
description: "Personal Site"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kasey McFadden"
resume_title:                   "CS @ Princeton"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kaseym@princeton.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "732-675-3994"
resume_contact_address:         ""

resume_header_contact_info:     "http://linkedin.com/in/kaseymcfadden/ • 732-675-3994 • kaseym@princeton.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm a software developer and current undergraduate student at Princeton University pursuing an engineering bachelor's degree in computer science. I'm thinking about concentrating in Machine Learning & Statistics or Cognitive Science.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kasey-mcfadden"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://linkedin.com/in/kaseymcfadden"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://kasey-mcfadden.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
